INSERT INTO "statuses_table" VALUES
(1, 1, 'Учится'),
(2, 1, 'Выпущен'),
(3, 1, 'Отчислен');
INSERT INTO "groups_table" VALUES
(4, 1, 'Английский'),
(5, 1, 'Французский');
INSERT INTO "contacts_table" VALUES
(6, 1, 'vdora@mail.ru', 'Вольдемар', 'Дора', 4, 1),
(7, 1, 'vlad@mail.ru', 'Влад', 'Цепеш', 5, 1),
(8, 1, 'arabiancat@mail.ru', 'Кшк', 'Транспэрэнт', 4, 1),
(9, 1, 'deviltrigger@mail.ru', 'Неру', 'Грин', 4, 1),
(10, 1, 'chippinin@mail.ru', 'Кекури', 'Рэд', 4, 1),
(11, 1, 'kflake@mail.ru', 'Каэли', 'Блу', 4, 1),
(12, 1, 'rollingstone@mail.ru', 'Крис', 'Крос', 5, 1),
(13, 1, 'beerhero@belka.ru', 'Бролин', 'Древоног', 4, 1),
(14, 1, 'neveraskedforthis@mail.ru', 'Фил', 'Дейтон', 4, 1),
(15, 1, 'stfuandtakemymoney@mail.ru', 'Фео', 'Дейтон', 5, 1),
(16, 1, 'fightclub@mail.ru', 'Тайлер', 'Дерден', 4, 1),
(17, 1, 'eeveefoot@mail.ru', 'Иви', 'Айронфут', 4, 1),
(18, 1, 'notatelepat@mail.ru', 'Аня', 'Форджер', 5, 1),
(19, 1, 'damnbro@mail.ru', 'Дэмн', 'Бро', 4, 1),
(20, 1, 'notanecromancer@belka.ru', 'Нимли', 'Древоног', 5, 1),
(21, 1, 'koshkomoozh@belka.ru', 'Ивин', 'Железноног', 4, 1),
(22, 1, 'imbatman@mail.ru', 'Кристиан', 'Бейл', 4, 1),
(23, 1, 'nobeaches@mail.ru', 'Мартин', 'Септимий', 4, 1),
(24, 1, 'diedofcringe@mail.ru', 'Уриэль', 'Септимий', 4, 1),
(25, 1, 'midgethater@mail.ru', 'Сайрус', 'Сайрусов', 4, 1),
(26, 1, 'aphelyismydaddy@mail.ru', 'Джироламо', 'Афельев', 4, 1),
(27, 1, 'imkamenshik@belka.ru', 'Зортана', 'Камневластная', 4, 1),
(28, 1, 'deadinsidik@belka.ru', 'Гроин', 'Ворчливый', 4, 1),
(29, 1, 'gdespirt@mail.ru', 'Геральт', 'Ривийский', 4, 1),
(30, 1, 'yesbeaches@mail.ru', 'Лютик', 'Блин', 5, 1),
(31, 1, 'godlikerat@belka.ru', 'Френк', 'Древоног', 4, 1),
(32, 1, 'noteevee@mail.ru', 'Элис', 'Эмберфист', 4, 1),
(33, 1, 'deadinsidik2@mail.ru', 'Кенри', 'Грейхарт', 4, 1),
(34, 1, 'paczan@belka.ru', 'Эйгон', 'Древоног', 5, 1),
(35, 1, 'realgod@belka.ru', 'Вектор', 'Имба', 5, 1);